---
- name: Check SSH Key Directory
  stat:
    path: "{{ ssh_key_dir }}"
  register: dir_stat

- name: Create SSH Key Directory
  file:
    path: "{{ ssh_key_dir }}"
    state: directory
  when: not dir_stat.stat.exists

- name: Generate SSH Key Pair
  shell: >
    ssh-keygen -t rsa -b 2048 -C "{{ ssh_key_comment }}"
    -f "{{ ssh_key_dir }}/{{ ssh_key_comment }}"
    -N "{{ ssh_key_passphrase }}"

- name: Fetch Public Key
  fetch:
    src: "{{ ssh_key_dir }}/{{ ssh_key_comment }}.pub"
    dest: "../ssh/{{ ssh_key_comment }}.pub"
    mode: "0755"
    flat: yes
