---
- name: Copy centos7.4 ks automatically answer files
  copy: src=centos-7.4-x86_64.cfg dest=/tmp/
  tags: images_centos7_4

- name: Copy the script that imports centos7.4 the mirror
  template: src={{ item }} dest=/tmp/
  with_items:
    - cobbler_image_import.sh
  tags: images_centos7_4

- name: Import_images_centos7_4
  shell: sh /tmp/cobbler_image_import.sh centos7_4
  tags: images_centos7_4
