---
- name: Copy centos6.5 ks automatically answer files
  copy: src=centos-6.5-x86_64.cfg dest=/tmp/
  tags: images_centos6_5

- name: Copy the script that imports centos6.5 the mirror
  template: src={{ item }} dest=/tmp/
  with_items:
    - cobbler_image_import.sh
  tags: images_centos6_5

- name: Import_images_centos6_5
  shell: sh /tmp/cobbler_image_import.sh centos6_5
  tags: images_centos6_5
